import fs from 'fs';
import path from 'path';

const DB_PATH = path.join(process.cwd(), 'src', 'data', 'database.json');

const fullSeriesList = [
  // 1. THỂ LOẠI: TU TIÊN / LUYỆN ĐAN / HỆ THỐNG
  {
    id: 'series-phe-vat',
    slug: 'phe-vat-ngu-hanh-linh-can-ta-co-than-thu-luyen-phe-duoc-thanh-bao-dan',
    title: 'Phế Vật Ngũ Hành Linh Căn, Ta Có Thần Thụ Luyện Phế Dược Thành Bảo Đan',
    description: 'Thiếu niên bị coi là phế vật ngũ hành tạp linh căn, cả đời không thể đột phá Trúc Cơ. Bất ngờ thức tỉnh Thần Thụ không gian, có khả năng luyện hóa phế đan thành cực phẩm thần đan, từ đó nghịch thiên cải mệnh, trấn áp vạn tộc!',
    thumbnail: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    channelName: 'Đại Đạo Review',
    channelAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    categories: ['Tu Tiên', 'Huyền Huyễn', 'Nghịch Thiên', 'Hệ Thống'],
    totalEpisodes: 7,
    featured: true,
    updatedAt: '2026-09-16',
    episodes: [
      {
        id: 'ep-1-1',
        seriesId: 'series-phe-vat',
        partNumber: 1,
        title: 'Tập 1: Bị tông môn ruồng bỏ, cơ duyên nhặt được Thần Thụ',
        originalUrl: 'https://www.facebook.com/reel/2294631994663679',
        embedUrl: 'https://www.facebook.com/plugins/video.php?href=' + encodeURIComponent('https://www.facebook.com/reel/2294631994663679') + '&show_text=0&autoplay=0',
        platform: 'facebook',
        aspectRatio: '9:16',
        duration: '01:30',
        viewsCount: 35400,
        publishedAt: '2026-09-10',
      },
      {
        id: 'ep-1-2',
        seriesId: 'series-phe-vat',
        partNumber: 2,
        title: 'Tập 2: Luyện hóa phế đan, tu vi tăng vọt kinh động Ngoại môn',
        originalUrl: 'https://www.facebook.com/reel/2294631994663679',
        embedUrl: 'https://www.facebook.com/plugins/video.php?href=' + encodeURIComponent('https://www.facebook.com/reel/2294631994663679') + '&show_text=0&autoplay=0',
        platform: 'facebook',
        aspectRatio: '9:16',
        duration: '01:40',
        viewsCount: 28200,
        publishedAt: '2026-09-11',
      },
      {
        id: 'ep-1-6',
        seriesId: 'series-phe-vat',
        partNumber: 6,
        title: 'Tập 6: Đột phá Trúc Cơ đỉnh phong, không áp chế nổi nữa!',
        originalUrl: 'https://www.facebook.com/reel/2294631994663679',
        embedUrl: 'https://www.facebook.com/plugins/video.php?href=' + encodeURIComponent('https://www.facebook.com/reel/2294631994663679') + '&show_text=0&autoplay=0',
        platform: 'facebook',
        aspectRatio: '9:16',
        duration: '01:45',
        viewsCount: 41200,
        publishedAt: '2026-09-15',
      },
      {
        id: 'ep-1-7',
        seriesId: 'series-phe-vat',
        partNumber: 7,
        title: 'Tập 7: Đại náo Thiên Kiếm Môn, trảm sát Trưởng lão phản bội',
        originalUrl: 'https://www.facebook.com/reel/172523643211485',
        embedUrl: 'https://www.facebook.com/plugins/video.php?href=' + encodeURIComponent('https://www.facebook.com/reel/172523643211485') + '&show_text=0&autoplay=0',
        platform: 'facebook',
        aspectRatio: '9:16',
        duration: '01:50',
        viewsCount: 29800,
        publishedAt: '2026-09-16',
      },
    ],
  },

  // 2. THỂ LOẠI: TRỌNG SINH / BÁ ĐẠO
  {
    id: 'series-tien-ton-trong-sinh',
    slug: 'trong-sinh-do-thi-tu-tien-tran-bac-huyen',
    title: 'Trọng Sinh Đô Thị Tu Tiên - Trần Bắc Huyền Trở Lại Địa Cầu',
    description: 'Độ kiếp kỳ Tiên Tôn Trần Phàm thất bại khi vượt thiên kiếp, trùng sinh trở lại thời niên thiếu tại Địa Cầu. Kiếp trước bị khinh rẻ chà đạp, kiếp này một tay nghịch thiên, lấy danh Trần Bắc Huyền quét ngang toàn cầu!',
    thumbnail: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?w=800&auto=format&fit=crop&q=80',
    channelName: 'Bá Đạo Anime',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    categories: ['Trọng Sinh', 'Đô Thị', 'Tu Tiên', 'Vô Địch Lưu'],
    totalEpisodes: 5,
    featured: false,
    updatedAt: '2026-09-16',
    episodes: [
      {
        id: 'ep-tbh-1',
        seriesId: 'series-tien-ton-trong-sinh',
        partNumber: 1,
        title: 'Tập 1: Tiên Tôn tỉnh giấc giữa giảng đường đại học',
        originalUrl: 'https://www.facebook.com/reel/2294631994663679',
        embedUrl: 'https://www.facebook.com/plugins/video.php?href=' + encodeURIComponent('https://www.facebook.com/reel/2294631994663679') + '&show_text=0&autoplay=0',
        platform: 'facebook',
        aspectRatio: '9:16',
        duration: '01:30',
        viewsCount: 52000,
        publishedAt: '2026-09-12',
      },
      {
        id: 'ep-tbh-2',
        seriesId: 'series-tien-ton-trong-sinh',
        partNumber: 2,
        title: 'Tập 2: Một chưởng phế bỏ thiếu gia đắc tội',
        originalUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        embedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=0&rel=0',
        platform: 'youtube',
        aspectRatio: '16:9',
        duration: '10:15',
        viewsCount: 38000,
        publishedAt: '2026-09-13',
      },
    ],
  },

  // 3. THỂ LOẠI: HUYỀN HUYỄN / NHIỆT HUYẾT
  {
    id: 'series-dau-pha',
    slug: 'dau-pha-thuong-khung-ba-nam-chi-uoc',
    title: 'Đấu Phá Thương Khung: Ba Năm Chi Ước - Tiêu Viêm Lên Vân Lam Tông',
    description: 'Ba mươi năm Hà Đông, ba mươi năm Hà Tây, đừng khinh thiếu niên nghèo! Tiêu Viêm một mình độc hành lên Vân Lam Tông thực hiện lời thề ước định 3 năm năm xưa với Nạp Lan Yên Nhiên.',
    thumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
    channelName: 'Mê Hoạt Hình 3D',
    channelAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80',
    categories: ['Tu Tiên', 'Huyền Huyễn', 'Nhiệt Huyết'],
    totalEpisodes: 3,
    featured: false,
    updatedAt: '2026-09-14',
    episodes: [
      {
        id: 'ep-dp-1',
        seriesId: 'series-dau-pha',
        partNumber: 1,
        title: 'Tập 1: Tiêu Viêm đặt chân lên đỉnh Vân Lam Sơn',
        originalUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        embedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=0&rel=0',
        platform: 'youtube',
        aspectRatio: '16:9',
        duration: '15:20',
        viewsCount: 145000,
        publishedAt: '2026-08-20',
      },
    ],
  },

  // 4. THỂ LOẠI: KHOA HUYỄN 3D / TƯƠNG LAI
  {
    id: 'series-thon-phe',
    slug: 'thon-phe-tinh-khong-dai-ket-cuc',
    title: 'Thôn Phệ Tinh Không: Tinh Cầu Tiến Hóa & Vũ Trụ Bí Cảnh',
    description: 'Địa Cầu tao ngộ đại tai biến RR virus hoành hành, La Phong từ một thanh niên khu ổ chuột nỗ lực trở thành Vũ Giả, lĩnh ngộ Cửu Trọng Lôi Đao rồi bước ra vũ trụ bao la mênh mông.',
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    channelName: 'Huyền Thoại 3D',
    channelAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    categories: ['Khoa Huyễn 3D', 'Huyền Huyễn', 'Tu Chân'],
    totalEpisodes: 4,
    featured: false,
    updatedAt: '2026-09-15',
    episodes: [
      {
        id: 'ep-tp-1',
        seriesId: 'series-thon-phe',
        partNumber: 1,
        title: 'Tập 1: Đại Niết Bàn thức tỉnh Tinh Thần Niệm Sư',
        originalUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        embedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=0&rel=0',
        platform: 'youtube',
        aspectRatio: '16:9',
        duration: '18:20',
        viewsCount: 98000,
        publishedAt: '2026-09-01',
      },
    ],
  },

  // 5. THỂ LOẠI: NGHỊCH THIÊN / MA ĐẠO
  {
    id: 'series-tien-nghich',
    slug: 'tien-nghich-vuong-lam-nghich-menh-tu-tien',
    title: 'Tiên Nghịch 3D: Vương Lâm Nhặt Được Thiên Nghịch Châu',
    description: 'Thuận vi phàm, nghịch vi tiên, chỉ tại nhất niệm gian! Vương Lâm tư chất bình thường, gia tộc bị diệt, một lòng bước vào con đường sát phạt tu tiên, trở thành sát thần chấn động tu chân giới.',
    thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
    channelName: 'Tu La Review',
    channelAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    categories: ['Tu Tiên', 'Nghịch Thiên', 'Ma Đạo'],
    totalEpisodes: 3,
    featured: false,
    updatedAt: '2026-09-16',
    episodes: [
      {
        id: 'ep-tn-1',
        seriesId: 'series-tien-nghich',
        partNumber: 1,
        title: 'Tập 1: Hằng Nhạc Phái cầu đạo, rơi xuống vực sâu',
        originalUrl: 'https://www.facebook.com/reel/2294631994663679',
        embedUrl: 'https://www.facebook.com/plugins/video.php?href=' + encodeURIComponent('https://www.facebook.com/reel/2294631994663679') + '&show_text=0&autoplay=0',
        platform: 'facebook',
        aspectRatio: '9:16',
        duration: '01:35',
        viewsCount: 45000,
        publishedAt: '2026-09-14',
      },
    ],
  },

  // 6. THỂ LOẠI: HÀI HƯỚC / THẦN THOẠI
  {
    id: 'series-tay-du',
    slug: 'tay-du-ky-hau-truyen-ngo-khong-dai-chien-vo-thien',
    title: 'Tây Du Ký 3D: Tôn Ngộ Không Đại Chiến Ma La Vô Thiên',
    description: 'Tam giới đại loạn, Như Lai viên tịch, Ma La Vô Thiên thống trị thiên đình. Tôn Ngộ Không một mình tìm kiếm 17 viên xá lợi tử để cứu vãn tam giới chúng sinh.',
    thumbnail: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80',
    channelName: 'Thần Thoại 3D',
    channelAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    categories: ['Huyền Huyễn', 'Thần Thoại', 'Nhiệt Huyết'],
    totalEpisodes: 2,
    featured: false,
    updatedAt: '2026-09-15',
    episodes: [
      {
        id: 'ep-td-1',
        seriesId: 'series-tay-du',
        partNumber: 1,
        title: 'Tập 1: Hắc Liên hoa nở, tam giới nguy cơ',
        originalUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        embedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=0&rel=0',
        platform: 'youtube',
        aspectRatio: '16:9',
        duration: '14:00',
        viewsCount: 76000,
        publishedAt: '2026-09-10',
      },
    ],
  }
];

fs.writeFileSync(DB_PATH, JSON.stringify(fullSeriesList, null, 2), 'utf-8');
console.log('✅ Đã cập nhật đầy đủ các thể loại phim vào database.json thành công!');
